### PR TITLE
Added a libunwind8-dev package to Debian/Ubuntu dependencies

### PR DESCRIPTION
**Pull request by Taritsyn**

### CODE REVIEW

**Comment by obastemur** [comment]
ChakraCore doesn't need that dependency anymore. Curious why you wanted to add?

**Comment by Taritsyn** [comment]
Hello, Oguz!

Try to build the [ChakraCore version 1.4.3](https://github.com/Microsoft/ChakraCore/releases/tag/v1.4.3) for Ubuntu 16.04 (x64) without `libunwind8-dev` package.

**Comment by obastemur** [comment]
Well, You shouldn't :)

1.4.3 is Windows only release. If you are interested using ChakraCore on Linux/OSX, use release/2.0 branch instead

**Comment by obastemur** [comment]
@Taritsyn is it possible for you to update your PR? i.e. you may add to the document (these steps apply to release/2.0 .. if you compile older versions you might need this that package?) 

This way, we may help others doing the same? /cc @liminzhu  ?

**Comment by obastemur** [comment]
LGTM

**Comment by obastemur** [comment]
@Taritsyn Thanks for your contribution!

**Pull request merged**
